/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Swagger Petstore - OpenAPI 3.0
 * This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
Swagger at [http://swagger.io](http://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
You can now help us improve the API whether it's by making changes to the definition itself or to the code.
That way, with time, we can improve the API in general, and expose some of the new features in OAS3.

Some useful links:
- [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
- [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
 * OpenAPI spec version: 1.0.17
 */
import {
  rest
} from 'msw'
import {
  faker
} from '@faker-js/faker'

export const getGetInventoryMock = () => ({
        'clfmjk2480000j0uh9wwecwfm': faker.datatype.number({min: undefined, max: undefined})
      })

export const getPlaceOrderMock = () => ({id: faker.helpers.arrayElement([faker.datatype.number({min: undefined, max: undefined}), undefined]), petId: faker.helpers.arrayElement([faker.datatype.number({min: undefined, max: undefined}), undefined]), quantity: faker.helpers.arrayElement([faker.datatype.number({min: undefined, max: undefined}), undefined]), shipDate: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined]), status: faker.helpers.arrayElement([faker.helpers.arrayElement(['placed','approved','delivered']), undefined]), complete: faker.helpers.arrayElement([faker.datatype.boolean(), undefined])})

export const getGetOrderByIdMock = () => ({id: faker.helpers.arrayElement([faker.datatype.number({min: undefined, max: undefined}), undefined]), petId: faker.helpers.arrayElement([faker.datatype.number({min: undefined, max: undefined}), undefined]), quantity: faker.helpers.arrayElement([faker.datatype.number({min: undefined, max: undefined}), undefined]), shipDate: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined]), status: faker.helpers.arrayElement([faker.helpers.arrayElement(['placed','approved','delivered']), undefined]), complete: faker.helpers.arrayElement([faker.datatype.boolean(), undefined])})

export const getStoreMSW = () => [
rest.get('*/store/inventory', (_req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
ctx.json(getGetInventoryMock()),
        )
      }),rest.post('*/store/order', (_req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
ctx.json(getPlaceOrderMock()),
        )
      }),rest.get('*/store/order/:orderId', (_req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
ctx.json(getGetOrderByIdMock()),
        )
      }),rest.delete('*/store/order/:orderId', (_req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
        )
      }),]
